version: '3.9'
services:
  node-rest-server:
    image: node-rest-server:1.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: node-rest-server
    environment:
      - PORT=${PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DOMAIN=${MONGO_DOMAIN}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_PORT=${MONGO_PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - "mongodb"
  mongodb:
    image: mongo:6.0.3
    container_name: mongodb
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb:/data/db
      - ./database/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  mongodb: {}